### ISSUE TITLE
[Peer Testing] Input not recognised when spacings are used

### ISSUE THREAD

**Issue by paturikarthik** [AY2324S2-CS2113-T11-2/tp#219]
![image](https://github.com/AY2324S2-CS2113-T11-2/tp/assets/64789669/486cdd28-db3d-4577-8d55-d77fdffde29e)
When there are no spaces, the command input is not recognised

**Comment by soongensayo** [comment]
<img width="1005" alt="Screenshot 2024-04-14 at 11 45 16 PM" src="https://github.com/AY2324S2-CS2113-T11-2/tp/assets/110648719/31c9fc18-1627-46ed-9084-8338084c106e">
