### ISSUE TITLE
[Peer Testing] anniversary date allows for date input later than today

### ISSUE THREAD

**Issue by owx0130** [AY2324S2-CS2113-T11-2/tp#233]
![image](https://github.com/AY2324S2-CS2113-T11-2/tp/assets/110607839/9407a970-8cb0-4b13-a480-f5f04638f97d)

As per screenshot, when asking for anniversary date input, user can input a date later than today, which does not make much sense

**Comment by soongensayo** [comment]
thanks, fixed
