### ISSUE TITLE
[Peer Testing] app crashes after data file is manually edited and "idea" is run

### ISSUE THREAD

**Issue by owx0130** [AY2324S2-CS2113-T11-2/tp#235]
![image](https://github.com/AY2324S2-CS2113-T11-2/tp/assets/110607839/5de8bbe1-69f8-404c-8032-78ea28f6cde8)

If user edits the data file as such, and inputs the `idea` command after relaunching the app, the program will crash

![image](https://github.com/AY2324S2-CS2113-T11-2/tp/assets/110607839/f5b2b3ef-c94c-4a6a-a7bf-4176ba56e850)

**Comment by soongensayo** [comment]
<img width="995" alt="Screenshot 2024-04-15 at 12 51 47 AM" src="https://github.com/AY2324S2-CS2113-T11-2/tp/assets/110648719/ef95bc0e-246c-4b73-9c54-052f88a8d734">
thanks, fixed
