### ISSUE TITLE
[Peer Testing] app crash on startup if data file is sufficiently edited

### ISSUE THREAD

**Issue by owx0130** [AY2324S2-CS2113-T11-2/tp#239]
![image](https://github.com/AY2324S2-CS2113-T11-2/tp/assets/110607839/04bf69a7-71d8-471e-8069-d6c9c9ed9061)

managed to crash the app using this data file

**Comment by soongensayo** [comment]
<img width="1060" alt="Screenshot 2024-04-15 at 12 50 11 AM" src="https://github.com/AY2324S2-CS2113-T11-2/tp/assets/110648719/e11db716-c56f-49eb-bbc5-0d85011fdfcb">
thanks, fixed
