### ISSUE TITLE
[Peer testing] Sequence diagram return arrow should be dashed i think

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-T11-2/tp#245]
![image](https://github.com/AY2324S2-CS2113-T11-2/tp/assets/76645229/a991c39a-d7db-46d5-9878-f56c95475bf8)
![image](https://github.com/AY2324S2-CS2113-T11-2/tp/assets/76645229/f8ab5b57-2a17-409c-83d7-31ce7530aff3)

**Comment by soongensayo** [comment]
thanks, fixed
